version: '3'
services:
    gz_bootstrap:
        #image: asdlfkj31h/garmin-opentopo:0.9
        image: asdlfkj31h/garmin-opentopo:latest
        command: /opt/garmin/bin/prepare_sea.sh
        volumes:
        - garminmaps:/garmin/
        - bounds:/garmin/var/bounds/
        - sea:/garmin/var/sea


    #mt_bootstrap:
    #    image: asdlfkj31h/garmin-opentopo:latest
    #    command: /opt/garmin/bin/prepare_fzk.sh
    #    volumes:
    #    - garminmaps:/garmin/
    #    - bounds:/garmin/bounds
    #    - sea:/garmin/sea        

    workflow:
        #image: asdlfkj31h/garmin-opentopo:0.9
        image: asdlfkj31h/garmin-opentopo:latest
        command: /opt/garmin/bin/fzk_workflow.sh
        environment: 
            region: "Freizeitkarte_RHEINLAND-PFALZ"
            lang: "de"
            typ: "opentopomap"
            style: "opentopomap"
        volumes:
            - bounds:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/bounds:ro
            - sea:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/sea:ro
            - install:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/install
            - work:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/work    


    mt:
        #image: asdlfkj31h/garmin-opentopo:0.9
        image: asdlfkj31h/garmin-opentopo:latest
        command: find /opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/work
        environment: 
            region: "Freizeitkarte_RHEINLAND-PFALZ"
            lang: "de"
        volumes:
            - garminmaps:/garmin/
            - bounds:/garmin/bounds/:ro
            - sea:/garmin/sea/:ro
            - install:/garmin/map_gps:ro
            - bounds:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/bounds:ro
            - sea:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/sea:ro
            - install:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/install
            - work:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/work        
