app:
    build: .
    #image: sdlfkj31h/garmin-opentopo:0.0.1
    #command: /usr/bin/xeyes
    volumes:
     - garmin_download:/garmin/var/download
     - garmin_sea:/garmin/var/sea
     - garmin_bounds:/garmin/var/bounds
download:
    build: .
    command: ./bin/prepare_sea.sh
    volumes:
     - garmin_download:/garmin/var/download
     - garmin_sea:/garmin/var/sea
     - garmin_bounds:/garmin/var/bounds
