version: '3'
services:
    prepare:
        image: asdlfkj31h/garmin-opentopo:latest
        command: /opt/garmin/bin/20_prepare_osm_tiles.sh
        environment: 
            region: "Freizeitkarte_RHEINLAND-PFALZ"
        volumes:
            - garminmaps:/garmin/
            - bounds:/garmin/var/bounds/
            - sea:/garmin/var/sea
            - bounds:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/bounds:ro
            - sea:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/sea:ro
            - work:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/work    

    prepare_typ:
        image: asdlfkj31h/garmin-opentopo:latest
        command: /opt/garmin/bin/30_prepare_typ.sh
        volumes:
            - work:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/work    

    render_map:
        image: asdlfkj31h/garmin-opentopo:latest
        command: /opt/garmin/bin/render_map.sh
        environment: 
            region: "Freizeitkarte_RHEINLAND-PFALZ"
            lang: "de"
            typ: "OpenTopoMap-Cave.typ" #"OpenTopoMap.typ"  # fenix-6x.typ            # freizeitkarte.TYP
            style: "opentopomap"    # fzk (auch bei fenix 6)
        volumes:
            - bounds:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/bounds:ro
            - sea:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/sea:ro
            - install:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/install
            - work:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/work    

    mt:
        image: asdlfkj31h/garmin-opentopo:latest
        command: ls # find /opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/work
        environment: 
            region: "Freizeitkarte_RHEINLAND-PFALZ"
            lang: "de"
            typ: "OpenTopoMap-Cave.typ" 
            style: "opentopomap" 
        volumes:
            - garminmaps:/garmin/
            - bounds:/garmin/bounds/:ro
            - sea:/garmin/sea/:ro
            - install:/garmin/map_gps:ro
            - bounds:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/bounds:ro
            - sea:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/sea:ro
            - install:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/install
            - work:/opt/lib/fzk-mde-garmin-develop/Freizeitkarte-Entwicklung/work        
